---Query 1---
SELECT F_NAME, L_NAME FROM EMPLOYEES
WHERE ADDRESS LIKE '%Elgin,IL';

---Query 2---
SELECT F_NAME, L_NAME FROM EMPLOYEES
WHERE B_DATE LIKE '197%';

---Query 3---
SELECT * FROM EMPLOYEES 
WHERE DEP_ID=5 AND SALARY BETWEEN 60000 AND 70000;


---Query 4---
SELECT * FROM EMPLOYEES 
ORDER BY DEP_ID;

---QUERY 5---
SELECT F_NAME, L_NAME, DEP_ID FROM EMPLOYEES
ORDER BY DEP_ID DESC, L_NAME;

---Query 6---
SELECT E.F_NAME, E.L_NAME, D.DEP_NAME FROM EMPLOYEES AS E, DEPARTMENTS AS D
WHERE E.DEP_ID = D.DEPT_ID_DEP
ORDER BY D.DEP_NAME, E.L_NAME DESC; 


---Query 7---
SELECT DEP_ID, COUNT(EMP_ID) AS NUM_EMPLOYEES FROM EMPLOYEES 
GROUP BY DEP_ID;

---Query 8---
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES 
GROUP BY DEP_ID;

---Query 9---
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES 
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

---QUERY 10---
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;
